name: mpserver-demo-01
services:
  my-hello-world:
    type: mpserver
    image: crccheck/hello-world
    ports: 
      - protocol: "http"
        number: 8000
    cpu: "200m"
    env: 
      - name: regcred
        valueFrom: 
          secretKeyRef:
            name: regcred
            key: .dockerconfigjson
    configmap:
      - name: istio-ca-root-cert
        mountPath: /app/istio
    httproute:
      gateways: ["external-gateway"]
      hosts: ["hello-world.default.testing.mpengine"]
      servernamespace: default
      serverport: 8000
    hpa:
      min: 1
      max: 1
      cpuPercent: 80

