name: grpc-exmaple-helloworld
services:

  grpc-exmaple-helloworld:
    type: mpserver
    image: docker.io/shikanon096/grpc-helloworld
    env:
      - name: PODNAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: PODIP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    ports: 
      - protocol: "tcp"
        number: 8000
