name: mpserver-kafka
services:

  test-deploy-kafka: # kafka workload
    type: mpserver
    image: wurstmeister/kafka:2.12-2.5.0
    env:
      - name: KAFKA_ADVERTISED_LISTENERS
        value: "INSIDE://test-deploy-kafka:9092,OUTSIDE://test-deploy-kafka.rcmd.testing.mpengine:10000"
      - name: KAFKA_LISTENERS
        value: "INSIDE://:9092,OUTSIDE://:10000"
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      - name: KAFKA_INTER_BROKER_LISTENER_NAME
        value: "INSIDE"
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: test-deploy-zookeeper:2181
      - name: KAFKA_BROKER_ID
        value: "0"
    ports: 
      - protocol: "tcp"
        number: 8000
    
  test-deploy-zookeeper: # zookeeper workload
    type: mpserver
    image: bitnami/zookeeper:3.6.2
    env:
      - name: ALLOW_ANONYMOUS_LOGIN
        value: "yes"
      - name: ZOO_SERVER_ID
        value: "1"
      - name: ZOO_SERVERS
        value: 0.0.0.0:2888:3888
    ports: 
      - protocol: "tcp"
        number: 2181
      - protocol: "tcp"
        number: 2888
      - protocol: "tcp"
        number: 3888