name: demo-iris-01
services:
  demo-iris:
    type: mpserver
    image: swr.cn-north-4.myhuaweicloud.com/hw-zt-k8s-images/sklearnserver:demo-iris
    ports: 
      - protocol: "http"
        number: 8000
    cpu: "200m"
    memory: "250Mi"
    httproute:
      gateways: ["external-gateway"]
      hosts: ["demo-iris.rcmd.testing.mpengine"]
      servernamespace: rcmd
      serverport: 8080
    hpa:
      min: 1
      max: 1
      cpuPercent: 60

