apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: jupyterhub
  namespace: default
spec:
  components:
    - name: jupyterhub-component
      type: micro-service
      properties:
        image: jupyterhub/jupyterhub-demo:1.4
        cmd: 
          - jupyterhub
          - --port=$(EXPORTPORT)
        env:
        - name: "EXPORTPORT"
          value: "8888"
        port:
        - protocol: "http"
          number: 8888
        volumes:
        - name: "jupyterhub-component-config"
          mountPath: "/home/work/bin/abtestdata/"
          type: "configMap"
          cmName: "jupyterhub-component-config"

