apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: abtestdata
spec:
  components:
    - name: jupyterhub-component-with-ingressgateway
      type: micro-service
      properties:
        image: jupyterhub/jupyterhub-demo:1.4
        cmd: 
          - jupyterhub
          - --port=$(EXPORTPORT)
        env:
        - name: "EXPORTPORT"
          value: "8888"
        port:
        - protocol: "http"
          number: 8888
        volumes:
        - name: "jupyterhub-component-config"
          mountPath: "/home/work/bin/abtestdata/"
          type: "configMap"
          cmName: "jupyterhub-component-config"
      traits:
      - type: ingressgateway
        properties:
          gateway: "internal-gateway"
          hosts: ["persona-query.cn-bj.rcmd-testing.skyengine.net.cn"]
          exportport: 8000