apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: jupyterhub-component-with-addvolume
spec:
  components:
    - name: jupyterhub-component-with-addvolume
      type: micro-service
      properties:
        image: jupyterhub/jupyterhub-demo:1.4
        cmd: 
          - jupyterhub
          - --port=$(EXPORTPORT)
        env:
        - name: "EXPORTPORT"
          value: "8888"
        port:
        - protocol: "http"
          number: 8888
        volumes:
        - name: "jupyterhub-component-config"
          mountPath: "/home/work/bin/abtestdata/"
          type: "configMap"
          cmName: "jupyterhub-component-config"
        - name: jupyter-test-pvc
          type: pvc
          claimName: jupyter-test-pvc
          mountPath: /home/data
      traits:
      - type: addvolume
        properties:
          name: jupyter-test-pvc
          pvc: "sas"
          size: 1
          region: "cn-north-4"
          zone: "g"