apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: add-account
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "the patch of deployment node to use custom service account"
spec:
  appliesToWorkloads:
    - deployments.apps
    - statefulsets.apps
  podDisruptive: true
  schematic:
    cue:
      template: |
        patch: {
          spec: template: spec: {
            serviceAccount: parameter.name
            serviceAccountName: parameter.name
          }
        }

        parameter: {
            // +usage=Expect the name of serviceAccount
            name: string
        }