apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: inject-sidecar
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "inject the sidecar image, is only support micro-service"
spec:
  appliesToWorkloads:
    - deployments.apps
  schematic:
    cue:
      template: |
        patch: {
          // +patchKey=name
          spec: template: spec: containers: [{
            name: parameter.name
            image: parameter.image
            if parameter["cmd"] != _|_ {
              command: parameter.cmd
            }
            if parameter["env"] != _|_ {
              env: parameter.env
            }
            if parameter["cpu"] != _|_ {
              resources: {
                limits:
                  cpu: parameter.cpu
                requests:
                  cpu: parameter.cpu
              }
            }
            if parameter["memory"] != _|_ {
              resources: {
                limits:
                  memory: parameter.memory
                requests:
                  memory: parameter.memory
              }
            }
          }]
        }

        parameter: {
          name: string
          image: string
          // +usage=Sidecar Commands to run in the container
          cmd?: [...string]
          // +usage=Define arguments by using environment variables in sidecar
          env?: [...{
            // +usage=Environment variable name
            name: string
            // +usage=The value of the environment variable
            value?: string
          }]
          // +usage=Number of CPU units for the service, like `0.5` (0.5 CPU core), `1` (1 CPU core)
          cpu?: string
          // +usage=Specifies the attributes of the memory resource required for the container.
          memory?: string
        }